### ISSUE TITLE
Camera going through the rock

### ISSUE THREAD

**Issue by mijar** [xstefank/Trolling#21]

**Comment by xstefank** [comment]
this will be harder than I expected, in unity it is impossible to have collisions without rigidbody set, which is unacceptable by our game

**Comment by xstefank** [comment]
not possible to fix fully, because we got obstacles in a way of the camera and if we don't want to make it stuck somewhere this is just impossible. I adjusted the problematic place in earth lvl so the camera won't collide: 3b0303e687afb683cd1bba65b831e49a810fdd30.
