### ISSUE TITLE
Tutorial level - idea

### ISSUE THREAD

**Issue by mijar** [xstefank/Trolling#22]
1) Initial animation, keyboard off - Juma wakes up in a forest, stands up, camera is animated from the front view to the 3rd person view.
2) Juma is standing (Idle animation) in tree corridor, keyboard on - a label with movement controls emerges, stays visible until the user moves Juma, then disappears.
3) He reaches a fallen tree - a label with Spacebar to jump emerges, same as before.
4) A flying bee appears in his path, a label with attack key emerges. 
5) He reaches a portal in a huge tree in the corridor - switch to animation
6) camera animation to see his front, curious look behind him and then he goes into the portal....
7) dip to black
8) shows up at the level hub.

Your comments?

**Comment by xstefank** [comment]
great, exactly what we need

**Comment by Alkanthor** [comment]
agreed

**Comment by mijar** [comment]
done.
