### ISSUE TITLE
drowning animation for JUMA

### ISSUE THREAD

**Issue by xstefank** [xstefank/Trolling#26]

**Comment by xstefank** [comment]
I need this to enhance the dying at the end of the animation, current workaround takes down 2 lives instead of one

**Comment by mijar** [comment]
You have got it in your mailbox. Git will not let me pull thus I am not able to commit it.

**Comment by mijar** [comment]
Philippino connection fail:
_fatal: The remote end hung up unexpectedly_
...

**Comment by mijar** [comment]
Hmm....after 1 hour of trying to commit, it was enough to say 'fuck this shit I go to bed', write here, send you an email...and the internet connection for git started working....
So it's in the repository, sorry.

**Comment by xstefank** [comment]
can you please send me rope climb or climbing with rope animation with character arm-space set to max ?

**Comment by mijar** [comment]
email
