### ISSUE TITLE
change GUI appearance (lives and points)

### ISSUE THREAD

**Issue by mijar** [xstefank/Trolling#29]
...As shown in tutorial level....I don't know if it's prefab or not or what.

**Comment by xstefank** [comment]
You can do this yourself if you want. All of the prefabs are in the Prefab folder. If it isn't there then it doesn't exist. :)

**Comment by mijar** [comment]
Done except the ice level - thus I am assigning this to Lubor. 
Fixed also the visibility of GUI in Game over scene.
