### ISSUE TITLE
earth level

### ISSUE THREAD

**Issue by xstefank** [xstefank/Trolling#4]
all ideas and work around earth level

**Comment by Alkanthor** [comment]
I started working on earth based lvl. Adding more infolater.

**Comment by Alkanthor** [comment]
Uploaded basic earth lvl model. I might add more obstacles later, but I think, the coridor itself is done.

**Comment by Alkanthor** [comment]
I added my model of earth enemy, altough we can definetely use it in other levels, too. Im kinda satisfied with its upper half, however it still needs some work on waist and legs. You can also try some animation. If you are interested, you can look here: https://www.mixamo.com/

**Comment by xstefank** [comment]
It would be useful, if you could post an image of the model here in the issue every time you push some graphical changes. "if you are interested" is really not what this project should be about, if you do not want to do it yourself create a new issue called "earth enemy animation" or something else.

**Comment by Alkanthor** [comment]
*if you are interested in the way, how to simply rig and animate character. It was meant as a tip, if you decided to start your own.

**Comment by Alkanthor** [comment]
I couldnt attach .avi file, so you I added it as a commit.
![smasher](https://cloud.githubusercontent.com/assets/14862341/10698902/9eee453c-79b3-11e5-8de2-881a6c0f2dee.jpg)

**Comment by xstefank** [comment]
I personally like it more just with 2 hands ;), I created a separate issue for enemy. #7
