### ISSUE TITLE
tutorial level played only once

### ISSUE THREAD

**Issue by mijar** [xstefank/Trolling#43]
It will be better, if the tutorial level was played once, to not to play it again if the player died and game over scene appeared....but he/she wants to play the game again (pressed New game button).
Do you agree?

**Comment by mijar** [comment]
I think it is related to the game manager the closest, so I assign Lubor.

**Comment by lubor-slusny** [comment]
more related to what have become of MenuBehaviourScript 
but should be easy to add

**Comment by lubor-slusny** [comment]
done
