### ISSUE TITLE
fire level - not dying after contact with lava

### ISSUE THREAD

**Issue by mijar** [xstefank/Trolling#44]
always happened when having 1 life only, few obstacles before the first enemy. the player falls through lava and is falling down...so I can play endlessly 
also the bottom texture of skybox is not there.

**Comment by mijar** [comment]
ok, it happens always when having only one life left. just try to get drowned enough times.:-)

**Comment by xstefank** [comment]
game manager.... again, this is singleton taken from level to lvl, generated in main menu. so if you want to die, something must process it, and this is the responsibility of gamemanger instance... please do not start your levels directly from level scene but from main menu shortcut...
