### ISSUE TITLE
character controls

### ISSUE THREAD

**Issue by Alkanthor** [xstefank/Trolling#5]
After landing the character goes into some sort of crouch state and when the surface is sloping, he glides back a little. Therefore, you have issues, when you want to jump for the second time. We might deal with this first so we are able to adjust the difficulty of obstacles in our levels. Try first part of earth level. I think, the last platform should be accessible.

**Comment by xstefank** [comment]
I plan to completely rewrite the whole moving script, you will be able to move in air like you were on the ground, also immediately jump again when you land

**Comment by xstefank** [comment]
moved to #8 closing this issue
